### ISSUE TITLE
Error signing v19R6

### ISSUE THREAD

**Issue by AlfonsoIdem** [miyako/4d-plugin-xmlsec#7]
Hello Miyako.

Mac OS 12.6.1
4D 19R6.282985

At time of execute  xmlsec sign

We get the error failed:xmlSecDSigCtxSign

In all your examples

In v18 it works fine.

**Comment by AlfonsoIdem** [comment]
Hello Miyako.

We can not update to v19R6 or R7 because this problem. 
Would you please see this issue at soon as possible.
T.I.A.

**Comment by AlfonsoIdem** [comment]
Hello.
It seems to work in 4DR7.100131

**Comment by miyako** [comment]
so we can close this?

**Comment by miyako** [comment]
very bizarre, I wonder what was wrong with R6.
